"""adde foregn key to student

Revision ID: b493e7a88454
Revises: 5b2d6180b3db
Create Date: 2025-09-19 09:48:56.359475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b493e7a88454'
down_revision = '5b2d6180b3db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_member_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'member', ['created_by_member_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by_member_id')

    # ### end Alembic commands ###
